from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QMutex
from PyQt5.QtWidgets import QMessageBox
from extendedEuclideanAlgorithm import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(599, 513)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(40, 80, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label1.setFont(font)
        self.label1.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label1.setWordWrap(True)
        self.label1.setObjectName("label1")
        self.label6 = QtWidgets.QLabel(self.centralwidget)
        self.label6.setGeometry(QtCore.QRect(50, 250, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label6.setFont(font)
        self.label6.setAlignment(QtCore.Qt.AlignCenter)
        self.label6.setObjectName("label6")
        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setGeometry(QtCore.QRect(40, 200, 501, 28))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.button.setFont(font)
        self.button.setObjectName("button")
        self.programName = QtWidgets.QLabel(self.centralwidget)
        self.programName.setGeometry(QtCore.QRect(20, 20, 541, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.programName.setFont(font)
        self.programName.setAlignment(QtCore.Qt.AlignCenter)
        self.programName.setObjectName("programName")
        self.result = QtWidgets.QTextBrowser(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(160, 430, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.result.setFont(font)
        self.result.setObjectName("result")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(40, 130, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label2.setFont(font)
        self.label2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label2.setWordWrap(True)
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(40, 300, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label3.setFont(font)
        self.label3.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label3.setWordWrap(True)
        self.label3.setObjectName("label3")
        self.lineEditB = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditB.setGeometry(QtCore.QRect(160, 140, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditB.setFont(font)
        self.lineEditB.setObjectName("lineEditB")
        self.lineEditA = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditA.setGeometry(QtCore.QRect(160, 90, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditA.setFont(font)
        self.lineEditA.setObjectName("lineEditA")
        self.label4 = QtWidgets.QLabel(self.centralwidget)
        self.label4.setGeometry(QtCore.QRect(40, 350, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label4.setFont(font)
        self.label4.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label4.setWordWrap(True)
        self.label4.setObjectName("label4")
        self.label5 = QtWidgets.QLabel(self.centralwidget)
        self.label5.setGeometry(QtCore.QRect(40, 430, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label5.setFont(font)
        self.label5.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label5.setObjectName("label5")
        self.resultX = QtWidgets.QTextBrowser(self.centralwidget)
        self.resultX.setGeometry(QtCore.QRect(160, 310, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.resultX.setFont(font)
        self.resultX.setObjectName("resultX")
        self.resultY = QtWidgets.QTextBrowser(self.centralwidget)
        self.resultY.setGeometry(QtCore.QRect(160, 360, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.resultY.setFont(font)
        self.resultY.setObjectName("resultY")

        self.lineEditA.setMaxLength(2147483647)
        self.lineEditB.setMaxLength(2147483647)
        reg_ex = QtCore.QRegExp("0|([1-9][0-9]*)")
        self.lineEditA.setValidator(QtGui.QRegExpValidator(reg_ex, self.lineEditA))
        self.lineEditB.setValidator(QtGui.QRegExpValidator(reg_ex, self.lineEditB))

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.msg = QMessageBox()
        self.msg.setIcon(QMessageBox.Warning)
        self.msg.setWindowTitle("Ошибка")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self._mutex = QMutex()
        self.addFunctions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "РАЕ"))
        self.label1.setText(_translate("MainWindow", "A = "))
        self.label6.setText(_translate("MainWindow", "A*x + B*y = НОД(A, B)"))
        self.button.setText(_translate("MainWindow", "Рассчитать"))
        self.programName.setText(_translate("MainWindow", "Расширенный алгоритм Евклида"))
        self.label2.setText(_translate("MainWindow", "B = "))
        self.label3.setText(_translate("MainWindow", "x = "))
        self.label4.setText(_translate("MainWindow", "y = "))
        self.label5.setText(_translate("MainWindow", "НОД(A, B) = "))

    def addFunctions(self):
        self._mutex.lock()
        self.button.clicked.connect(self.extendedEuclideanAlgorithm)

    def showError(self, text1, text2=""):
        self.msg.setText(text1)
        self.msg.setInformativeText(text2)
        self.msg.exec_()

    def extendedEuclideanAlgorithm(self):
        a = self.lineEditA.text()
        b = self.lineEditB.text()
        if len(a) == 0 or len(b) == 0:
            self.showError("Введите параметры")
            return

        a, b = int(a), int(b)
        result, x, y = extendedEuclideanAlgorithm(a, b)
        print(result, x, y)
        self.resultX.setText(str(x))
        self.resultY.setText(str(y))
        self.result.setText(str(result))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
